import { describe, expect, it } from 'vitest';
import { createCartKey, isCartKey, readCookie } from '../lib/cart';
import { createGuestOrderToken, isGuestOrderToken } from '../lib/guest-token';
import { getAccessToken, getAuthenticatedIdentity } from '../lib/server-auth';

describe('cookie parsing', () => {
  it('fails closed for malformed guest cart cookies', () => {
    const request = new Request('http://localhost/api/cart', {
      headers: { cookie: 'nivara-cart-key=%E0%A4%A' },
    });

    expect(readCookie(request, 'nivara-cart-key')).toBeNull();
  });

  it('does not throw for malformed chunked auth cookies', async () => {
    const request = new Request('http://localhost/api/account/profile', {
      headers: { cookie: 'sb-demo-auth-token=%E0%A4%A' },
    });

    await expect(getAuthenticatedIdentity(request)).resolves.toBeNull();
  });

  it('reassembles auth cookie chunks in numeric order', () => {
    const serialized = JSON.stringify({ access_token: 'access-token' });
    const chunkSize = Math.ceil(serialized.length / 11);
    const cookies = Array.from({ length: 11 }, (_, index) => {
      const start = index * chunkSize;
      return `sb-demo-auth-token.${index}=${serialized.slice(start, start + chunkSize)}`;
    }).join('; ');
    const request = new Request('http://localhost/api/account/profile', {
      headers: { cookie: cookies },
    });

    expect(getAccessToken(request)).toBe('access-token');
  });

  it('decodes a direct access-token cookie', () => {
    const request = new Request('http://localhost/api/account/profile', {
      headers: { cookie: 'nivara-access-token=%22access%2Btoken%22' },
    });

    expect(getAccessToken(request)).toBe('access+token');
  });

  it('only accepts cart keys generated by the server', () => {
    expect(isCartKey(createCartKey())).toBe(true);
    expect(isCartKey('attacker-controlled-cart-key')).toBe(false);
    expect(isCartKey('a'.repeat(25))).toBe(false);
  });

  it('only accepts guest order tokens generated by the server', () => {
    expect(isGuestOrderToken(createGuestOrderToken().rawToken)).toBe(true);
    expect(isGuestOrderToken('secret')).toBe(false);
    expect(isGuestOrderToken('a'.repeat(44))).toBe(false);
  });
});
