"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Heart, Menu, Search, ShoppingBag, Sparkles, Truck, X } from "lucide-react";
import { categories, formatInr, products } from "@/lib/demo-data";

function ProductCard({ product, onAdd }: { product: (typeof products)[number]; onAdd: () => void }) {
  return <article className="group"><div className="product-image relative overflow-hidden rounded-[1.5rem] bg-[#e8e0d4]"><img src="/nivara-editorial.png" alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" style={{ objectPosition: product.imagePosition }} /><div className="absolute inset-0 bg-gradient-to-t from-[#1d2820]/25 via-transparent to-transparent" />{product.badge && <span className="absolute left-3 top-3 rounded-full bg-[#fffaf3]/90 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-[#314338]">{product.badge}</span>}<button type="button" aria-label={`Save ${product.name} to wishlist`} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-[#fffaf3]/90 text-[#314338]"><Heart size={16} strokeWidth={1.8} /></button>{product.stock > 0 && <button type="button" onClick={onAdd} className="absolute bottom-3 left-3 right-3 rounded-full bg-[#314338] px-4 py-3 text-sm font-semibold text-[#fffaf3] opacity-0 shadow-lg transition group-hover:opacity-100 focus:opacity-100 hover:bg-[#26372c]">Add to bag</button>}</div><div className="mt-4 flex items-start justify-between gap-3"><div><Link href={`/product/${product.slug}`} className="font-semibold tracking-[-0.02em] hover:text-[#a6503d]">{product.name}</Link><p className="mt-1 text-sm text-[#718078]">{product.category}</p></div><div className="text-right text-sm font-semibold"><p>{formatInr(product.price)}</p>{product.compareAt && <p className="mt-1 text-xs font-normal text-[#9b9084] line-through">{formatInr(product.compareAt)}</p>}</div></div></article>;
}

export default function Home() {
  const [cartCount, setCartCount] = useState(0);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const addToBag = (name: string) => { setCartCount((count) => count + 1); setNotice(`${name} added to your bag.`); window.setTimeout(() => setNotice(""), 2600); };

  return <main className="min-h-screen bg-[#f8f4ee] text-[#27362d]"><div className="border-b border-[#ded7cc] bg-[#e7eee5] px-4 py-2 text-center text-xs font-semibold tracking-[0.08em] text-[#44574a]">Free delivery on orders over ₹999 · Thoughtful things for everyday living</div><header className="sticky top-0 z-30 border-b border-[#e5ddd2]/80 bg-[#f8f4ee]/95 backdrop-blur"><div className="mx-auto flex h-[4.75rem] max-w-[1240px] items-center justify-between gap-6 px-5 lg:px-8"><Link href="/" className="flex items-center gap-3" aria-label="Nivara home"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#c6674f] text-sm font-bold text-[#fffaf3]">N</span><span className="font-display text-2xl font-semibold tracking-[-0.06em]">nivara</span></Link><nav className="hidden items-center gap-8 text-sm font-semibold text-[#536259] md:flex" aria-label="Primary navigation"><Link href="/shop" className="hover:text-[#a6503d]">Shop</Link><Link href="/shop?sort=newest" className="hover:text-[#a6503d]">New arrivals</Link><Link href="/shop?sort=best" className="hover:text-[#a6503d]">Best sellers</Link><a href="#about" className="hover:text-[#a6503d]">About</a></nav><div className="flex items-center gap-1"><button type="button" aria-label="Search" className="hidden h-10 w-10 place-items-center rounded-full hover:bg-[#ece5da] sm:grid"><Search size={18} strokeWidth={1.8} /></button><Link href="/account" aria-label="Account" className="hidden h-10 w-10 place-items-center rounded-full hover:bg-[#ece5da] sm:grid"><span className="text-sm font-semibold">◌</span></Link><Link href="/checkout" aria-label={`Bag with ${cartCount} items`} className="relative grid h-10 w-10 place-items-center rounded-full hover:bg-[#ece5da]"><ShoppingBag size={18} strokeWidth={1.8} />{cartCount > 0 && <span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-[#c6674f] px-1 text-[10px] font-bold text-white">{cartCount}</span>}</Link><button type="button" aria-label="Open menu" onClick={() => setMobileOpen((open) => !open)} className="grid h-10 w-10 place-items-center rounded-full hover:bg-[#ece5da] md:hidden">{mobileOpen ? <X size={18} /> : <Menu size={18} />}</button></div></div>{mobileOpen && <nav className="border-t border-[#e5ddd2] bg-[#fffaf3] px-5 py-4 md:hidden" aria-label="Mobile navigation"><div className="grid gap-4 text-sm font-semibold"><Link href="/shop" onClick={() => setMobileOpen(false)}>Shop</Link><Link href="/shop?sort=newest" onClick={() => setMobileOpen(false)}>New arrivals</Link><Link href="/shop?sort=best" onClick={() => setMobileOpen(false)}>Best sellers</Link><a href="#about" onClick={() => setMobileOpen(false)}>About</a></div></nav>}</header>{notice && <output aria-live="polite" className="fixed bottom-5 left-1/2 z-40 -translate-x-1/2 rounded-full bg-[#314338] px-5 py-3 text-sm font-semibold text-white shadow-xl">{notice}</output>}
    <section className="mx-auto grid max-w-[1240px] gap-8 px-5 pb-16 pt-10 lg:grid-cols-[0.86fr_1.14fr] lg:items-center lg:px-8 lg:pb-24 lg:pt-16"><div className="max-w-[530px]"><p className="eyebrow"><Sparkles size={14} /> Small comforts, considered well</p><h1 className="font-display mt-5 text-[clamp(3rem,7vw,6.5rem)] font-semibold leading-[0.9] tracking-[-0.08em]">Make space for <em className="font-normal text-[#b25d49]">everyday.</em></h1><p className="mt-7 max-w-[430px] text-lg leading-8 text-[#64726a]">Practical, well-made pieces for desks, kitchens, and the first little corners that make a place feel like home.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/shop" className="button-primary">Shop the collection <ArrowRight size={16} /></Link><a href="#categories" className="button-secondary">Explore categories</a></div><div className="mt-10 flex items-center gap-4 text-sm text-[#718078]"><span className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f8f4ee] bg-[#d6b49c] text-xs">A</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f8f4ee] bg-[#aebca6] text-xs">R</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f8f4ee] bg-[#d8cfb9] text-xs">M</span></span><span>Made for first homes and fresh starts</span></div></div><div className="relative min-h-[420px] overflow-hidden rounded-[2rem] bg-[#c6d0c0] shadow-[0_20px_60px_rgba(52,64,53,0.12)] lg:min-h-[580px]"><img src="/nivara-editorial.png" alt="A calm first-apartment corner with a planter and desk essentials" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#27362d]/40 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 max-w-[220px] text-[#fffaf3]"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f2d4c8]">The soft landing edit</p><p className="mt-2 font-display text-3xl leading-none tracking-[-0.05em]">A little order, a little warmth.</p></div><span className="absolute right-7 top-7 grid h-16 w-16 place-items-center rounded-full bg-[#e48a6f] text-center text-xs font-bold uppercase leading-4 tracking-[0.08em] text-[#fffaf3]">New<br />season</span></div></section>
    <section id="categories" className="border-y border-[#e3dbd0] bg-[#fffaf3] px-5 py-12 lg:px-8"><div className="mx-auto max-w-[1240px]"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Browse by room</p><h2 className="section-title">Start with the corner you’re making yours.</h2></div><Link href="/shop" className="hidden items-center gap-2 text-sm font-bold text-[#a6503d] sm:flex">View all <ArrowRight size={15} /></Link></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{categories.map((category, index) => <Link key={category.name} href={`/shop?category=${encodeURIComponent(category.name)}`} className={`category-card category-${category.accent}`}><span className="text-xs font-bold uppercase tracking-[0.14em]">0{index + 1}</span><span className="mt-16 block text-xl font-semibold tracking-[-0.04em]">{category.name}</span><span className="mt-2 block text-sm opacity-75">{category.count} pieces</span><ArrowRight size={17} className="absolute bottom-5 right-5" /></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-16 lg:px-8 lg:py-24"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">A considered few</p><h2 className="section-title">Good things to come home to.</h2></div><Link href="/shop" className="hidden items-center gap-2 text-sm font-bold text-[#a6503d] sm:flex">Shop all pieces <ArrowRight size={15} /></Link></div><div className="mt-8 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} onAdd={() => addToBag(product.name)} />)}</div></section>
    <section id="about" className="mx-auto grid max-w-[1240px] gap-5 px-5 pb-16 lg:grid-cols-[1.1fr_0.9fr] lg:px-8 lg:pb-24"><div className="relative min-h-[360px] overflow-hidden rounded-[2rem] bg-[#d3daca]"><img src="/nivara-editorial.png" alt="A plant, basket, and desk objects styled in a calm home" className="absolute inset-0 h-full w-full object-cover" style={{ objectPosition: "78% 38%" }} /></div><div className="flex flex-col justify-center rounded-[2rem] bg-[#314338] p-8 text-[#fffaf3] lg:p-12"><p className="eyebrow text-[#d8c6a8]">Why Nivara</p><h2 className="mt-5 font-display text-4xl leading-[0.95] tracking-[-0.07em] lg:text-5xl">Useful can still feel personal.</h2><p className="mt-6 max-w-[390px] leading-7 text-[#d7e0d4]">We look for the pieces that do their job quietly, wear in beautifully, and make the everyday feel a touch more considered.</p><Link href="/shop" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#f3c4b4]">Meet the collection <ArrowRight size={16} /></Link></div></section>
    <section className="border-y border-[#e3dbd0] bg-[#e7eee5] px-5 py-10 lg:px-8"><div className="mx-auto grid max-w-[1240px] gap-8 sm:grid-cols-3"><div className="flex gap-4"><Truck className="mt-1 shrink-0 text-[#a6503d]" size={22} /><div><p className="font-semibold">Easy delivery</p><p className="mt-1 text-sm leading-6 text-[#637268]">Free over ₹999, otherwise ₹79 across India.</p></div></div><div className="flex gap-4"><span className="mt-1 grid h-[22px] w-[22px] shrink-0 place-items-center rounded-full border border-[#a6503d] text-xs font-bold text-[#a6503d]">↺</span><div><p className="font-semibold">Thoughtful returns</p><p className="mt-1 text-sm leading-6 text-[#637268]">Clear policies, no confusing fine print.</p></div></div><div className="flex gap-4"><span className="mt-1 grid h-[22px] w-[22px] shrink-0 place-items-center rounded-full border border-[#a6503d] text-xs font-bold text-[#a6503d]">✦</span><div><p className="font-semibold">Made for real homes</p><p className="mt-1 text-sm leading-6 text-[#637268]">Practical objects with a little personality.</p></div></div></div></section>
    <footer className="mx-auto flex max-w-[1240px] flex-col gap-4 px-5 py-10 text-sm text-[#718078] sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>© 2026 Nivara. Demonstration storefront.</p><div className="flex gap-5"><Link href="/support" className="hover:text-[#a6503d]">Support</Link><Link href="/policies" className="hover:text-[#a6503d]">Policies</Link><Link href="/admin" className="hover:text-[#a6503d]">Admin preview</Link></div></footer></main>;
}
